controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_joint_position_controller:
      type: forward_command_controller/ForwardCommandController

    arm_joint_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    arm_joint_effort_controller:
      type: forward_command_controller/ForwardCommandController

    gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    gains:
      fr3_joint1: { p: 600.0, d: 30.0, i: 0.0, i_clamp: 1.0 }
      fr3_joint2: { p: 600.0, d: 30.0, i: 0.0, i_clamp: 1.0 }
      fr3_joint3: { p: 600.0, d: 30.0, i: 0.0, i_clamp: 1.0 }
      fr3_joint4: { p: 600.0, d: 30.0, i: 0.0, i_clamp: 1.0 }
      fr3_joint5: { p: 250.0, d: 10.0, i: 0.0, i_clamp: 1.0 }
      fr3_joint6: { p: 150.0, d: 10.0, i: 0.0, i_clamp: 1.0 }
      fr3_joint7: { p: 50.0, d: 5.0, i: 0.0, i_clamp: 1.0 }

arm_joint_position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    interface_name: position

arm_joint_velocity_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    interface_name: velocity

arm_joint_effort_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    interface_name: effort

gripper_controller:
  ros__parameters:
    type: parallel_gripper_action_controller/GripperActionController
    joint: fr3_finger_joint1
