joint_limits:
  fr3_joint1:
    has_acceleration_limits: true
    max_acceleration: 3.75
  fr3_joint2:
    has_acceleration_limits: true
    max_acceleration: 1.875
  fr3_joint3:
    has_acceleration_limits: true
    max_acceleration: 2.5
  fr3_joint4:
    has_acceleration_limits: true
    max_acceleration: 3.125
  fr3_joint5:
    has_acceleration_limits: true
    max_acceleration: 3.75
  fr3_joint6:
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_joint7: 
    has_acceleration_limits: true
    max_acceleration: 5.0
  fr3_finger_joint1:
    has_acceleration_limits: true
    max_acceleration: 1.0
  fr3_finger_joint2:
    has_acceleration_limits: true
    max_acceleration: 1.0

    