/**: 
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz
      thread_priority: 98
      enable_overrun: false

      fr3_arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

/**:
  franka_robot_state_broadcaster:
    ros__parameters:
      lock_try_count: 5 # Number of attempts to acquire the lock in a single on_update()
      lock_sleep_interval: 5 # microseconds sleep between attempts
      lock_log_error: false #  Log error if lock acquisition fails - false == do not log  
      lock_update_success: true # return update OK, although lock fails (no update occurs)
      
/**: 
  fr3_arm_controller:
    ros__parameters:
      command_interfaces:
        - effort
      state_interfaces:
        - position
        - velocity
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
      gains:
        fr3_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
        fr3_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
        fr3_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }
