# NOTE: Modified from upstream franka_ros2 by hri_rlc.

controller_names:
  - fr3_arm_controller
  - fr3_gripper

fr3_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - fr3_joint1
    - fr3_joint2
    - fr3_joint3
    - fr3_joint4
    - fr3_joint5
    - fr3_joint6
    - fr3_joint7

fr3_gripper:
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - fr3_finger_joint1
      - fr3_finger_joint2
